### PR TITLE
Promisify apis

### LINKED ISSUE #71: Promisify APIs
We'll promisify fromXML & toXML APIs.

Related to: https://github.com/bpmn-io/bpmn-js/issues/812

### PR DESCRIPTION
**Pull request by oguzeroglu**
Closes #71

### CODE REVIEW

**Comment by oguzeroglu** [comment]
> Please get rid of `done` entirely. This means that patterns such as this:
> 
> ```js
> fromFile('test/fixtures/bpmn/error/no-xml.txt').catch(function(err) {
>    expect(err).to.exist;
>      done();
>    });
> });
> ```
> 
> ...should be transformed to `try { await ... } ...` blocks.

In this test we benefit from the done() behavior, as we'd like to check if fromFile fails. The alternative would be:

```javascript
var err;

try {
  // await stuff...
} catch(error){
  err = error;
}

except(err).not.to.be.undefined;
```

Which in my opinion is not prettier, nor not worth the effort just for the sake of getting rid of "done".

**Comment by nikku** [comment]
This does not only have the benefit of getting rid of done but also the benefit of being more understandable.

**Comment by oguzeroglu** [comment]
Updated the tests 👍

**Comment by nikku** [comment]
Added three changes on top:

* fix + modernize example: https://github.com/bpmn-io/bpmn-moddle/pull/73/commits/3610cd8f5eb1a937c48398cd9d3b9e60a243b907
* simplify read tests: https://github.com/bpmn-io/bpmn-moddle/pull/73/commits/0f59ee6fea1d6462e18e17317036022490f0feff

Both follow the pattern we're taking with `moddle-xml`.

**Comment by nikku** [comment]
Looking at the API I find it a bit odd that read returns a structured object (including warnings) while write returns the plain result (i.e. only the written XML string).

I remember we had an issue somewhere that write warnings are currently simply emitted to the console, as the current API does not support exposing it. Returning a complex object (`{ xml, warnings, ... }`) would allow us to export that meta-data in the future. It would also mean that we offer the same, semantic API for read and write.

Getting the XML would still be as simple as

```javascript
const { xml } = await moddle.write(definitions);
```

**Comment by oguzeroglu** [comment]
I updated the API accordingly, also squashed your commits.

**Pull request merged**
