### PR TITLE
fix: adjusted DataAssociation model to match bpmn spec

### PR DESCRIPTION
**Pull request by Skaiir**
Related to https://github.com/camunda/camunda-modeler/issues/2333

The spec reasons for this are referenced by our contributor on the above issue.

### CODE REVIEW

**Comment by Skaiir** [comment]
Looking around I didn't see specific testing of the name property, is this something that needs to be done here, or is it a bit redundant?

**Comment by nikku** [comment]
Any fix we shall apply [via a transform](https://github.com/bpmn-io/bpmn-moddle/blob/master/tasks/transforms/transformBPMN.js) from the original BPMN 2.0 meta-model.

Please add a test case, i.e. verify that a BPMN 2.0 spec compliant diagram with the name property on a data-association can be read and serialized.

**Comment by barmac** [comment]
Let's also add a test case to [the write tests](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/xml/write.js) and [the roundtrip tests](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/xml/roundtrip.js) so that we are sure the fix works fine. The roundtrip tests verify that the serialized is a proper BPMN according to the XSD schema.

**Review by barmac — COMMENTED** [review]
Let's also add a test case to [the write tests](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/xml/write.js) and [the roundtrip tests](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/xml/roundtrip.js) so that we are sure the fix works fine. The roundtrip tests verify that a serialized diagram is a proper BPMN according to the XSD schema.

**Comment by Skaiir** [comment]
Following discussions with @barmac, we have discovered that this issue is actually a bug in the bpmn specs. The pdf spec allows for the name, but the xml spec does not. Our approach is hence going to change here, as we do not want to support something which is potentially going to break other vendor's tools. We will use the XML as the true spec and instead change the properties panel to not anymore expose the name property. 

If my reasoning is appropriate, I am going to close this PR. @nikku @pinussilvestrus any objections?

**Comment by nikku** [comment]
@Skaiir Exactly. The XML schema has to be our reference here, no matter what the PDF says.

**Pull request closed without merging**
